name: Create all functions

on: [pull_request]

jobs:
  builds:
    runs-on: ubuntu-latest
    env:
      VERSION: "v1.15.1"
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install func
      run: |
        echo "Installing func ${{env.VERSION}}"
        program_url="https://github.com/knative/func/releases/download/knative-${{env.VERSION}}/func_linux_amd64"
        curl -SLO $program_url && mv func_linux_amd64 f && chmod +x f
        cp f /usr/local/bin
        f version

    - name: Build Functions
      run: |
        WORKDIR=$(mktemp -d)
        cd $WORKDIR
        ## NOTE: ls -d returns absolute path
        ## GITHUB_WORKSPACE is the root directory
        #cycle through all languages
        echo ">>> ${{ github.event.pull_request.title }}"
        url="http://github.com/gauron99/func-templates#${{ github.event.pull_request.title }}"
        echo ">> url is: $url"
        for lang_dir_abs in $(ls -d ${GITHUB_WORKSPACE}/*/); do
          echo "> ${GITHUB_WORKSPACE}"
          lang=$(basename "$lang_dir_abs")
          echo "Building funcs in language $lang"
          for template_dir_abs in $(ls -d $lang_dir_abs*/); do
            ls -la
            ls -la ${GITUB_WORKSPACE}
            template=$(basename "$template_dir_abs")
            echo "f create $lang-$template -r=$url -l=$lang -t=$template"
            f create $lang-$template -r "$url" -l "$lang" -t "$template"
            #FUNC_ENABLE_HOST_BUILDER=1 FUNC_BUILDER=host FUNC_CONTAINER=false FUNC_REGISTRY=docker.io/4141gauron3268 f 
          done
        done


