name: Build All on main

on: 
  push:
    branches: main

jobs:
  builds:
    runs-on: ubuntu-latest
    env:
      FUNC_VERSION: "knative-v1.16.1"
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install func
      uses: gauron99/knative-func-action@main
      with:
        version: ${{FUNC_VERSION}}
        name: f
    - name: Build Functions
      run: |
        WORKDIR=$(mktemp -d)
        cd $WORKDIR
        ## NOTE: ls -d returns absolute path
        ## GITHUB_WORKSPACE is the root directory  (checked out?)
        #cycle through all languages
        url="http://github.com/gauron99/func-templates"
        for lang_dir_abs in $(ls -d ${GITHUB_WORKSPACE}/*/); do
          lang=$(basename "$lang_dir_abs")
          echo "Building funcs in language $lang"
          for template_dir_abs in $(ls -d $lang_dir_abs*/); do
            template=$(basename "$template_dir_abs")
            ls -la $template_dir_abs
            echo "f create $lang-$template -r=$url -l=$lang -t=$template"
            f create $lang-$template -r "$url" -l "$lang" -t "$template"
            #FUNC_ENABLE_HOST_BUILDER=1 FUNC_BUILDER=host FUNC_CONTAINER=false FUNC_REGISTRY=docker.io/4141gauron3268 f 
          done
        done


